### ISSUE TITLE
Error:CUDA out of memory

### ISSUE THREAD

**Issue by WShihan** [jiupinjia/stylized-neural-painting#5]
This project is so cool and I want to run it on my PC, I downloaded  the repo,configured and the  error(CUDA out of memory) occurred.I change max_m_strokes ，max_divide two  parameters, it works correctly, but the outpu is not meet my demand. I know nothing about the torch framework, can you help me to solve this problem, please ?

**Comment by jiupinjia** [comment]
Thanks for your valuable feedback. Actually what you concerned about is exactly what I am working on these days. In the near further (hopefully next week), I will be adding a lightweight rendering model so that people with limited GPU memory can run smoothly on it and get high-resolution results. I will let you know when this feature is ready to use.

**Comment by jiupinjia** [comment]
Hi @WShihan, a few updates have been made that I believe would be useful for you:
1. We have provided some lightweight renderers where users now can easily generate high-resolution paintings with much more stroke details. With the lightweight renders, the rendering speed also improves a lot (x3 faster). This update also solves the out-of-memory problem when running our demo on a GPU card with limited memory (e.g. 4GB). 
2. Animated results are available at the output_dir (*_animated.mp4)
Please check out more details in the README file.

**Comment by WShihan** [comment]
Thank you so much,

**Comment by jiupinjia** [comment]
I'm closing this issue. Please feel free to leave your comment here if you have any future questions. Thanks!
