### ISSUE TITLE
cannot to connect to x window error on google colab

### ISSUE THREAD

**Issue by terekita** [jiupinjia/stylized-neural-painting#7]
Great project!!!

I'm trying to train my own strokes on google colab. However, when I try to run the demo:

`!python demo.py --img_path ./test_images/sunflowers.jpg --canvas_color 'white' --max_m_strokes 500 --m_grid 5 --renderer oilpaintbrush --renderer_checkpoint_dir checkpoints_G_oilpaintbrush --output_dir ./output`

I get this error:
initialize network with normal
loading renderer from pre-trained checkpoint...
begin to draw...
iteration step 0, G_loss: 0.00000, step_psnr: 4.52816, strokes: 25 / 500
: cannot connect to X server 

Guessing that it is some kind of image show function(s) somewhere...

**Comment by jiupinjia** [comment]
Hi @terekita, thanks for your feedback. Yes, you are right, the problem lies in the cv2.imshow() functions. Since u are running remotely, I would suggest you specify --disable_preview. I believe this would nicely solve your problem. 
Please check out [this tag](https://github.com/jiupinjia/stylized-neural-painting#running-through-ssh) in the README file for more details.

**Comment by terekita** [comment]
Thank you so much for your reply, and I apologize that I missed that import point in the readme! I am now able to train off my own images on colab. This is a completely awesome project, and many thanks for helping to run the code!

**Comment by jiupinjia** [comment]
You're good! Also, congratulations on your successful run!

**Comment by terekita** [comment]
Thanks! I had to go to the high-RAM session on colab pro, but having done that, it was all easy...Love this project!

**Comment by jiupinjia** [comment]
Great! But if you are having an out of memory problem, you can wait a few days since I am now exactly working on solving this issue. I am now training some more lightweight renderers so that with them hopefully everyone can generate more detailed painting with limited GPU memory in their local machine.

**Comment by jiupinjia** [comment]
Hi @terekita, a few updates have been made that I believe would be useful for you:

We have provided some lightweight renderers where users now can easily generate high-resolution paintings with much more stroke details. With the lightweight renders, the rendering speed also improves a lot (x3 faster). This update also solves the out-of-memory problem when running our demo on a GPU card with limited memory (e.g. 4GB).
Animated results are available at the output_dir (*_animated.mp4)

Please check out more details in the README file. You can try out the lightweight renderer on your local machine. I believe this version has improved a lot on your needs.

**Comment by terekita** [comment]
That is so awesome! Thank you so much for this wonderful project!
